version: '3'
services:
  vue-frontend:
    build: ./frontend
    command: bash -c "npm install && npm run serve"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - '8080:8080'

  node-server:
    build: ./server
    command: bash -c "npm install && npm run serve"
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '4000:4000'
